#set page(paper: "us-letter", margin: (x: 0.7in, y: 0.5in))
#set text(font: "Liberation Serif", size: 10pt)
#set par(leading: 0.65em, justify: false)
#set heading(numbering: "1.")

#import "@preview/tdtr:0.6.1": tidy-tree-draws, tidy-tree-graph

#let grammar(body) = block(
  width: 100%,
  inset: 10pt,
  radius: 4pt,
  fill: luma(246),
  stroke: 0.6pt + luma(210),
  body,
)

#let answer(body) = block(
  width: 100%,
  inset: (left: 10pt, right: 10pt, top: 7pt, bottom: 7pt),
  stroke: (left: 2pt + rgb("4b6b8a")),
  body,
)

#let parse-tree(body, text-size: 8pt, spacing: (5pt, 13pt)) = align(center)[
  #tidy-tree-graph(
    compact: true,
    text-size: text-size,
    spacing: spacing,
    node-inset: 1pt,
    draw-node: (stroke: none, defocus: 0),
    draw-edge: (
      tidy-tree-draws.south-north-draw-edge,
      (marks: "-"),
    ),
  )[#body]
]

#align(center)[
  #text(size: 16pt, weight: "bold")[COP4555 - Assignment 2]
]
#v(4pt)

= Grammar Derivations

#set heading(numbering: "1.a")

Given the grammar with start symbol $S$:

#grammar[
  #raw(block: true, lang: "text", "S -> 0Y | 1X\nX -> 0 | 0S | 1XX\nY -> 1 | 1S | 0YY")
]

== 00110101

#answer[
  #raw(
    block: true,
    lang: "text",
    "S\n-> 0Y\n-> 00YY\n-> 001SY\n-> 0011XY\n-> 00110SY\n-> 001101XY\n-> 0011010Y\n-> 00110101",
  )
]

== 1101101

#answer[
  The string can not be generated by the grammar. Starting from $S -> 1X$ has us needing terminal symbols incompatible with the remaining suffixes.
]

== 110001

#answer[
  #raw(block: true, lang: "text", "S\n-> 1X\n-> 11XX\n-> 110X\n-> 1100S\n-> 11000Y\n-> 110001")
]

#pagebreak()

= Parse Trees

#set heading(numbering: "1.1")

Given the grammar:

#grammar[
  #raw(
    block: true,
    lang: "text",
    "<assign>     -> <identifier> = <expression>\n<identifier> -> A | B | C\n<expression> -> <expression> + <term> | <term>\n<term>       -> <term> * <factor> | <factor>\n<factor>     -> ( <expression> ) | <identifier>",
  )
]

== A = A + (B + C \* A)

#parse-tree(text-size: 7.5pt, spacing: (4pt, 11pt))[
  - `<assign>`
    - `<identifier>`
      - `A`
    - `=`
    - `<expression>`
      - `<expression>`
        - `<term>`
          - `<factor>`
            - `<identifier>`
              - `A`
      - `+`
      - `<term>`
        - `<factor>`
          - `(`
          - `<expression>`
            - `<expression>`
              - `<term>`
                - `<factor>`
                  - `<identifier>`
                    - `B`
            - `+`
            - `<term>`
              - `<term>`
                - `<factor>`
                  - `<identifier>`
                    - `C`
              - `*`
              - `<factor>`
                - `<identifier>`
                  - `A`
          - `)`
]

== B = C * (A * C + B)

#parse-tree(text-size: 7.5pt, spacing: (4pt, 11pt))[
  - `<assign>`
    - `<identifier>`
      - `B`
    - `=`
    - `<expression>`
      - `<term>`
        - `<term>`
          - `<factor>`
            - `<identifier>`
              - `C`
        - `*`
        - `<factor>`
          - `(`
          - `<expression>`
            - `<expression>`
              - `<term>`
                - `<term>`
                  - `<factor>`
                    - `<identifier>`
                      - `A`
                - `*`
                - `<factor>`
                  - `<identifier>`
                    - `C`
            - `+`
            - `<term>`
              - `<factor>`
                - `<identifier>`
                  - `B`
          - `)`
]

#pagebreak()
= Proving BNF Ambiguity

A grammar is ambiguous if at least one string in its language has two distinct derivations.

== Grammar 1

#grammar[
  #raw(block: true, lang: "text", "S -> X | Y\nX -> xXy | xy\nY -> xyY | ε")
]

Consider the single string `xy`. It can be generated in two different ways:

#grid(
  columns: (1fr, 1fr),
  gutter: 18pt,
  [*Derivation 1* #raw(block: true, lang: "text", "S -> X -> xy")],
  [*Derivation 2* #raw(block: true, lang: "text", "S -> Y -> xyY -> xy")],
)

Because the same terminal string `xy` has two distinct derivations, the grammar is ambiguous.

== Grammar 2

#grammar[
  #raw(block: true, lang: "text", "<S> -> <A>a\n<S> -> a<A>\n<A> -> a\n<A> -> ε")
]

Consider the single string `aa`. It can also be generated in two different ways:

#grid(
  columns: (1fr, 1fr),
  gutter: 18pt,
  [*Derivation 1* #raw(block: true, lang: "text", "<S> -> <A>a -> aa")],
  [*Derivation 2* #raw(block: true, lang: "text", "<S> -> a<A> -> aa")],
)

Since the terminal string `aa` has two distinct derivations, this grammar is ambiguous as well.
